### ISSUE TITLE
No settings in StaffCP

### ISSUE THREAD

**Issue by tadhgboyle** [partydragen/Vote-Module#5]
Hi,
When I install this plugin I see a vote page in my navigation bar but it is empty and I can't see any config in the StaffCP.
Any help is nice,
Aber

**Comment by StormyIceLeopard** [comment]
I am having the same issue.
Vote Module (For v2.0.0 pr7) 2.0.0-pre7

**Comment by tadhgboyle** [comment]
Fixed by manually adding permissions in phpmyadmin
